networks:
  ai_network:
    driver: bridge

services:
  seed-vc:
    image: seed-vc:latest
    container_name: seed-vc
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/seed-vc/results:/code/results
      - d:/AI/seed-vc/error:/code/error
      - d:/AI/seed-vc/logs:/code/logs
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
      - CUDA_VISIBLE_DEVICES=1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    shm_size: '16g'
    ports:
      - '7869:7869'
    command: python /code/api.py --api True
    networks:
      - ai_network
